tap "envkey/envkey"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "awscli"
brew "axel"
brew "bat"
brew "composer"
brew "coreutils"
brew "diff-so-fancy"
brew "direnv"
brew "dive"
brew "dnsmasq"
# brew "envkey-fetch"  # not available on arm64.
# brew "envkey-source"  # not available on arm64.
brew "exiftool"
brew "ffmpeg"
brew "git-lfs"
brew "gnu-sed"
brew "gnu-tar"
brew "graphite2"
brew "graphviz"
brew "grep"
brew "htop"
brew "jq"
brew "kustomize"
brew "mysql-client"
brew "mtr"
brew "node"
brew "opus-tools"
brew "opusfile"
brew "p7zip"
brew "php@7.4"
# brew "php@7.3"  # not available on arm64.
brew "php"
brew "qrencode"
# brew "shellcheck"  # not available on arm64.
brew "socat"
brew "sqlite"
brew "starship"
brew "svn"
brew "telnet"
brew "terraform"
brew "tmux"
brew "tree"
brew "wget"
brew "youtube-dl"
brew "yq"

# Apps
# cask "1password"  # via App Store.
cask "1password-cli"
# cask "affinity-designer-beta"  # via App Store.
# cask "affinity-photo-beta"  # via App Store.
cask "android-file-transfer"
cask "android-studio"
cask "charles"
cask "docker"
cask "dropbox"
cask "envkey"
cask "firefox"
# cask "font-code"  # no longer available
cask "font-consolas-for-powerline"
cask "font-devicons"
# cask "font-droid-sans"  # no longer available
# cask "font-droid-sans-mono"  # no longer available
cask "font-droid-sans-mono-for-powerline"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-hack"
cask "font-hack-nerd-font"
# cask "font-hack-nerd-font-mono"  # no longer available
cask "font-inconsolata-dz-for-powerline"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-g-for-powerline"
cask "font-iosevka"
cask "font-iosevka-nerd-font"
cask "font-monoid"
# cask "font-noto-nerd-font-mono"  # no longer available
cask "font-roboto-mono"
cask "font-roboto-mono-for-powerline"
# cask "font-robotomono-nerd-font"  # no longer available
# cask "font-robotomono-nerd-font-mono"  # no longer available
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "hammerspoon"
cask "intellij-idea"
cask "iterm2"
cask "microsoft-excel"
cask "microsoft-word"
cask "mysqlworkbench"
cask "netspot"
cask "ngrok"
cask "obs"
cask "postman"
cask "rectangle"
# cask "slack"  # via App Store.
cask "soapui"
cask "steam"
cask "sublime-text"
cask "transmission"
# cask "tuntap"  # no longer available
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vlc"
# cask "wechat"  # via App Store.
# cask "whatsapp"  # via App Store.
cask "wine-stable"
cask "wkhtmltopdf"
