add_newline = true

[cmd_duration]
show_milliseconds = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[directory]
truncation_length = 7
truncation_symbol = ".../"
truncate_to_repo = false

[directory.substitutions]
"/Users/geoff" = "~"
"/Users/geoffrey.garbers" = "~"

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[helm]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[purescript]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = true

[singularity]
disabled = true

[status]
disabled = false

[swift]
disabled = true

[terraform]
format = "[$symbol$workspace]($style) "

[vagrant]
disabled = true

[zig]
disabled = true
